name: CI/CD

on:
  push:
    branches: [develop]

jobs: 
  build:
    runs-on: ubuntu-20.04
    

    steps:
      - uses: actions/checkout@v2


      - name: .env setting
        run: |
          touch .env 
          echo "REACT_APP_SERVER_IP=${{ secrets.REACT_APP_DEV_SERVER_IP }}" >> .env
   
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DEV_FRONTEND_APP_NAME}} -f ./Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DEV_FRONTEND_APP_NAME}}
          
      - name: Ec2 Docker run 
        uses: appleboy/ssh-action@master
        env:
          NAME: ${{ secrets.DOCKER_USERNAME }}
          APP: $ {{ secrets.DEV_FRONTEND_APP_NAME }}
          COMPOSE: docker-compose.yml
        with:
          username: ubuntu
          host: ${{ secrets.UBUNTU_DEV_HOST }}
          key: ${{ secrets.UBUNTU_DEV_KEY }}
          envs: APP, COMPOSE, NAME
          script_stop: true
          script: |
            sudo docker-compose -f $COMPOSE down --rmi all
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DEV_FRONTEND_APP_NAME }}
            sudo docker-compose -f $COMPOSE up -d 